# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 15:35
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('imagem', models.ImageField(blank=True, height_field='altura_imagem', null=True, upload_to=blog.models.upload_location, width_field='comprimento_imagem')),
                ('altura_imagem', models.IntegerField(default=0)),
                ('comprimento_imagem', models.IntegerField(default=0)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id', '-data_criacao', '-ultima_atualizacao'],
            },
        ),
    ]
