# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 23:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='admin', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='data_publicacao',
            field=models.DateField(default=datetime.datetime(2016, 3, 14, 23, 45, 8, 339893, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='rascunho',
            field=models.BooleanField(default=False),
        ),
    ]
